nodeLinker: node-modules
enableGlobalCache: false
logFilters:
  - code: YN0000
    text: "STDOUT **INFO**"
    level: discard
  - code: YN0000
    text: "chrome-headless-shell"
    level: discard
  - code: YN0000
    text: "chrome ("
    level: discard
  - code: YN0007
    level: discard