enableGlobalCache: false

logFilters:
  - code: YN0000
    level: discard
    text: STDOUT **INFO**
  - code: YN0000
    level: discard
    text: chrome-headless-shell
  - code: YN0000
    level: discard
    text: chrome (
  - code: YN0007
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.11.0.cjs
