# Jekyll Configuration for GitHub Pages
# This enables pretty URLs without .html extensions

# Permalink style - removes .html from URLs
permalink: pretty

# Exclude files from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - babel.config.js
  - eslint.config.js
  - jest.config.js
  - __tests__
  - coverage
  - README.md
  - LICENSE

# Keep the _headers file
include:
  - _headers
