// Auto-generated by Cloudflare Pages build
if (typeof window !== 'undefined') {
  window.TEST_RESULTS = {
    jest: {
      success: false,
      numTotalTests: 0,
      numPassedTests: 0,
      numFailedTests: 0,
      numTotalTestSuites: 0,
      numPassedTestSuites: 0,
      passRate: 0,
      avgDuration: 0,
      testSuites: [],
    },
    k6: {
      metrics: {
        http_reqs: {
          count: 0,
        },
        http_req_duration: {
          avg: 0,
          'p(95)': 0,
        },
        checks: {
          passes: 0,
          fails: 0,
        },
      },
    },
    coverage: {
      lines: {
        total: 0,
        covered: 0,
        pct: 0,
      },
      statements: {
        total: 0,
        covered: 0,
        pct: 0,
      },
      functions: {
        total: 0,
        covered: 0,
        pct: 0,
      },
      branches: {
        total: 0,
        covered: 0,
        pct: 0,
      },
    },
    metadata: {
      branch: 'cloudflare-build',
      commit: 'auto',
      timestamp: '2025-11-13T17:42:47.524Z',
      triggeredBy: 'cloudflare-pages',
    },
    generatedAt: '2025-11-13T17:42:47.524Z',
  };
  console.log('📊 Test dashboard: Data generated during Cloudflare Pages build');
}
