// Test results data file (auto-generated by CI/CD or local scripts)
// Run locally: ./update-test-reports.sh
// Production: Generated automatically by GitHub Actions on push
// This placeholder version is committed to prevent 404 errors on Cloudflare Pages

if (typeof window !== 'undefined') {
  window.TEST_RESULTS = {
    jest: {
      success: false,
      numTotalTests: 0,
      numPassedTests: 0,
      numFailedTests: 0,
      numTotalTestSuites: 0,
      numPassedTestSuites: 0,
      passRate: 0,
      avgDuration: 0,
      testSuites: [],
    },
    k6: {
      metrics: {
        http_reqs: { count: 0 },
        http_req_duration: { avg: 0, 'p(95)': 0 },
        checks: { passes: 0, fails: 0 },
      },
    },
    coverage: {
      lines: { total: 0, covered: 0, pct: 0 },
      statements: { total: 0, covered: 0, pct: 0 },
      functions: { total: 0, covered: 0, pct: 0 },
      branches: { total: 0, covered: 0, pct: 0 },
    },
    metadata: {
      branch: 'main',
      commit: 'placeholder',
      timestamp: new Date().toISOString(),
      triggeredBy: 'placeholder',
    },
    generatedAt: new Date().toISOString(),
  };

  console.log('📊 Test dashboard: Using placeholder data (run CI/CD to generate real results)');
}
